### ISSUE TITLE
Improvements for !parsemem

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RABot#27]
## 1. DONE! ~~If the argument is an achievement URL, parse the "Mem" of the achievement~~

example: `!mem https://retroachievements.org/achievement/9413`
improvement: `!mem ach=9413`

## 2. DONE! ~~Make it accept a string as the address/value~~

example: `!mem 0xHlevel=N`
output something like:
```
1: Mem 8-bit 0xlevel = N
```

**Note**:
- string length must be limited
- ???

## 3. DONE! ~~Make it have some aliases for templates~~

example: `!mem finishlevel`

**Comment by kdecks** [comment]
Due to an update in the in the 0.75 dll the first alt group is now name Alt 00 instead of 01. (It also allows you have just one alt, which is nice)
![image](https://user-images.githubusercontent.com/32706333/52527013-f3d78500-2c7e-11e9-91f7-3d50b2d8ebfb.png)

Posting this so the !mem command can accurately match the toolkit.

**Comment by meleu** [comment]
one last thing before closing this issue:

- when using `!mem https://retroachievements.org/achievement/{AchievementID}` in dev channels (jr-devs, devs-chat, code-reviewer, etc), show the Code Notes.
