### ISSUE TITLE
!mem command improvement

### ISSUE THREAD

**Issue by Keltron3030** [RetroAchievements/RABot#72]
When you invoke the `!mem` command the bot will interpret the inputted achievement logic and output achievement conditions in a more readable form as presented in the achievement editor.  

I've noticed that some logic flags do not display properly, in that they do not omit the operator and value/address/hits to the right of the operator. 

`!mem B:d0xh80dc=2_0xh80dc=2`

Current ouput:
![Screenshot_20210110-211143_Discord](https://user-images.githubusercontent.com/42773860/104142204-82337480-5388-11eb-86bb-7772f5301921.jpg)

Expected output:
![image](https://user-images.githubusercontent.com/42773860/104141949-41872b80-5387-11eb-973d-0bba01efa8e1.png)

Logic flags which should produce this behavior but do not:

Add Source
SubSource
AddAddress

**Comment by pinguupinguu** [comment]
Since the last post regarding this issue in January, we've had a couple of new logic features not supported by the bot either. Below is a list of them, and their relevant "raw text logic flags" taken from the CopyDef button in RALibRetro. As previously stated, operators and values should be ommitted from:

AddSource- Flag= `A:`
SubSource- Flag=`B:`
AddAddress - Flag=`I:`

Logic operands still not parsed that SHOULD have operators/values/hits:

ResetNextIf - Flag=`Z:`
Trigger - Flag=`T:`
SubHits - Flag=`D:`

**Comment by pinguupinguu** [comment]
Operators `/*&` for `AddSource` `SubSource` and `AddAddress` should also be displayed. Taken from 
[https://github.com/RetroAchievements/RAWeb/pull/570#issuecomment-843178082](url)
